# Generated by Django 3.2.13 on 2022-05-09 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=18)),
                ('is_delete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'userInfo',
            },
        ),
        migrations.AlterField(
            model_name='peopleinfo',
            name='gender',
            field=models.SmallIntegerField(choices=[(2, 'feamle'), (1, 'male')], default=1),
        ),
    ]
